# Generated by Django 4.2.26 on 2025-11-28 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='flow_document.incomingdocument'),
        ),
        migrations.AddConstraint(
            model_name='incomingdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user',), name='unique_draft_per_user'),
        ),
    ]
